# This workflow creates a release using goreleaser
# via the 'make release' command.

name: Create release

on:
  push:
    branches:
      - leo/test-new-release-ci

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: chain-runner
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Make release
        run: |
          make goreleaser-build-local
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
